// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXX78aQEmZyFLPlqhpercV7QxGkh01SsA',
    appId: '1:380895096424:web:2dacbf2936d3e210b155dd',
    messagingSenderId: '380895096424',
    projectId: 'qrmenu-dev-36a5e',
    authDomain: 'qrmenu-dev-36a5e.firebaseapp.com',
    databaseURL: 'https://qrmenu-dev-36a5e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrmenu-dev-36a5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSN3TUrOPaGxeEDsv3esZlPFQepZK4gVI',
    appId: '1:380895096424:android:ee56fd7ed7f90714b155dd',
    messagingSenderId: '380895096424',
    projectId: 'qrmenu-dev-36a5e',
    databaseURL: 'https://qrmenu-dev-36a5e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrmenu-dev-36a5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiRCFaaBarQG9xj9oBSkhe9kXj5kcQS-Q',
    appId: '1:380895096424:ios:133e9cf11e6a0d43b155dd',
    messagingSenderId: '380895096424',
    projectId: 'qrmenu-dev-36a5e',
    databaseURL: 'https://qrmenu-dev-36a5e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrmenu-dev-36a5e.appspot.com',
    iosBundleId: 'com.qrmenu.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiRCFaaBarQG9xj9oBSkhe9kXj5kcQS-Q',
    appId: '1:380895096424:ios:133e9cf11e6a0d43b155dd',
    messagingSenderId: '380895096424',
    projectId: 'qrmenu-dev-36a5e',
    databaseURL: 'https://qrmenu-dev-36a5e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qrmenu-dev-36a5e.appspot.com',
    iosBundleId: 'com.qrmenu.dev',
  );
}
